"""Add ForeignKey User <-> Products

Revision ID: f08a20d351cd
Revises: b14f4d6f6afd
Create Date: 2025-08-30 17:13:05.586228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f08a20d351cd"
down_revision: Union[str, Sequence[str], None] = "b14f4d6f6afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "product", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_column("product", "user_id")
    # ### end Alembic commands ###
